name: Build → ACR → AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myngnix:$IMAGE_TAG .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/myngnix:$IMAGE_TAG

    # AKS deleted — skipping deploy steps
    # - name: Set AKS context
    # - name: Deploy to AKS
