name: Build to ACR to AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myngnix:$IMAGE_TAG .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/myngnix:$IMAGE_TAG

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: AzureProject
        cluster-name: aks-firstazure

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/webapp webapp=${{ secrets.ACR_LOGIN_SERVER }}/myngnix:${{ github.sha }}
        kubectl rollout status deployment/webapp
